"""
test_plotting.py

Tests the ValidationPlotter using the selected
station and comparison generated by ComparisonManager.

Author:
3DPAWS Validation Toolkit
"""

from pathlib import Path

import config

from modules.report import ValidationReport
from modules.dataset_manager import DatasetManager
from modules.comparison_manager import ComparisonManager
from modules.plotting import ValidationPlotter
from modules.statistical_analysis import StatisticalAnalysis
from modules.results_exporter import (
    ValidationResultsExporter
)


def main():

    print("\n")
    print("=" * 80)
    print("TEST PLOTTING MODULE")
    print("=" * 80)

    # ------------------------------------------------------
    # Build Station Catalogue
    # ------------------------------------------------------

    dataset_manager = DatasetManager(

        root_folder=config.STATIONS_OUTPUT_DIR

    )

    stations = dataset_manager.run()

    # ------------------------------------------------------
    # Display Stations
    # ------------------------------------------------------

    print("\n")
    print("=" * 80)
    print("AVAILABLE STATIONS")
    print("=" * 80)

    print(
        f"{'No':>3} "
        f"{'Station':30}"
        f"{'3DPAWS':>10}"
        f"{'KMD':>10}"
    )

    print("-" * 80)

    for index, station in enumerate(
        stations,
        start=1
    ):

        print(
            f"{index:3d} "
            f"{station.display_name:30}"
            f"{station.paws_count:10d}"
            f"{station.kmd_count:10d}"
        )

    print("-" * 80)

    # ------------------------------------------------------
    # Select Station
    # ------------------------------------------------------

    while True:

        selection = input(
            "\nEnter station number (Q to Quit): "
        ).strip()

        if selection.upper() == "Q":

            print("\nGoodbye.")

            return

        try:

            selection = int(selection)

            if 1 <= selection <= len(stations):

                break

            print("Invalid station number.")

        except ValueError:

            print("Please enter a valid number.")

    station = stations[selection - 1]

    # ------------------------------------------------------
    # Run Comparison Manager
    # ------------------------------------------------------

    comparison = ComparisonManager(

        station

    )

    job = comparison.run()

    if job is None:

        print(
            "\nComparison could not be completed."
        )

        return

    # ------------------------------------------------------
    # Run Statistical Analysis
    # ------------------------------------------------------

    analysis = StatisticalAnalysis(
        job
    )

    results = analysis.run()

    # ------------------------------------------------------
    # Determine comparison period
    # ------------------------------------------------------

    if (

        job.overlap_start.year
        == job.overlap_end.year

        and

        job.overlap_start.month
        == job.overlap_end.month

    ):

        period = (

            f"{job.overlap_start:%Y-%m}"

        )

    else:

        period = (

            f"{job.overlap_start:%Y-%m}"
            "_to_"
            f"{job.overlap_end:%Y-%m}"

        )

    # ------------------------------------------------------
    # Dynamic output folder
    # ------------------------------------------------------

    station_folder = (

        Path(job.paws.filepath)
        .parent
        .parent

    )

    output_folder = (

        station_folder
        / "Comparison_Graphs"
        / period

    )

    # ------------------------------------------------------
    # ------------------------------------------------------
    # Create Plotter
    # ------------------------------------------------------

    plotter = ValidationPlotter(
        comparison_data=job.merged_data,
        output_folder=output_folder,
        station_name=job.paws.station,
        period=period,
        data_quality=job.data_quality,
        statistics_results=results
    )

    # ------------------------------------------------------
    # ------------------------------------------------------
    # Generate graphs
    # ------------------------------------------------------

    plotter.run()

    print("\n")
    print("=" * 80)
    print("GRAPHS GENERATED")
    print("=" * 80)

    print(
        f"\nGraphs saved to:\n"
        f"{output_folder}"
    )
    # ------------------------------------------------------
    # Export Station Validation Results
    # ------------------------------------------------------

    results_folder = (
        output_folder
        / "Results"
    )

    exporter = ValidationResultsExporter(

        station_name=job.paws.station,

        period=period,

        results=results,

        output_folder=results_folder,

    )

    results_path = exporter.export()
    # ------------------------------------------------------
    # Generate Word Report
    # ------------------------------------------------------

    report = ValidationReport(
        job=job,
        statistics_results=results,
        graphs_folder=output_folder
    )

    report_path = report.generate()

    print("\n")
    print("=" * 80)
    print("VALIDATION TEST COMPLETED")
    print("=" * 80)

    print(
        f"\nGraphs saved to:\n"
        f"{output_folder}"
    )

    print(
        f"\nWord report saved to:\n"
        f"{report_path}"
    )
# ==========================================================
# ENTRY POINT
# ==========================================================

if __name__ == "__main__":

    main()